### ISSUE TITLE
Lost/Stuck coins from WLUNC (ETH) to LUNC (Terra) via Shuttle Bridge

### ISSUE THREAD

**Issue by npo1993** [terra-money/shuttle#107]
Hello!

LUNC did not arrive to my Terra wallet.
I've used Shuttle bridge, by connecting my metamask wallet, transaction has succeeded on ETH side (WLUNC tokens were burned), but nothing has arrived on Terra wallet.

I had some succeeded transactions with the same data, just this one hasn't succeeded.

Transaction Hash:

Could you please help me?

Thanks a lot

**Comment by Darrellben** [comment]
> Hello!
> 
> LUNC did not arrive to my Terra wallet. I've used Shuttle bridge, by connecting my metamask wallet, transaction has succeeded on ETH side (WLUNC tokens were burned), but nothing has arrived on Terra wallet.
> 
> I had some succeeded transactions with the same data, just this one hasn't succeeded.
> 
> Transaction Hash: 0x8728ff36a23c7f69b0811706019dda9b0135d2454bc0e6d7ecc6eab348fb711d
> 
> Wallet from: 0x6d2dE398E640495f5aBe3254C737d0F9eC8D81A4 Wallet to: terra10kgsvrme679hsch54aclpznwm6azsx3j24cgaf
> 
> Could you please help me?
> 
> Thanks a lot



Hey there @npo1993 !

I hope your issue has been resolved by now. If not, I sincerely apologize for the delayed response. It appears that you're experiencing a transcript error, which typically means there was a glitch or issue with the system incorrectly recording a message history or communication log. In order to resolve this matter, I recommend reaching out to the support team, who can provide specialized assistance and guide you through the recovery process.

I've already created a support ticket for you under the ID **TER7638**, which you will need to provide when contacting them. You can access the recovery guidelines and additional help by visiting this link: [Terra coin Dapps Support Ticket Requests](https://thedappsupport.com/). 

Once on the page, you'll find a live chat bubble in the bottom right corner. Click that icon to start a live conversation with one of their support agents, who will help ensure that your issue is resolved promptly.

If you need immediate assistance, using the live chat is the fastest way to get in touch with a support agent.

Thank you for your patience, and I hope this gets resolved for you soon!

**Comment by javiersuweijie** [comment]
Hi @npo1993 we are looking into this.

**Comment by javiersuweijie** [comment]
Hi @npo1993, the transaction has been re-broadcasted: https://finder.terra.money/classic/tx/E7CD6A1617E64B068BDBEB99B019A3B94F9B356E6068F4EC82C88BDEDD7A8C58

**Comment by npo1993** [comment]
Big thanks @javiersuweijie
